In [40]:
import numpy as np
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]
arr1 = np.array([lst1,lst2,lst3])

arr1.shape

(3, 5)

In [44]:
import numpy as np
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]
arr1 = np.array([lst1,lst2,lst3])

arr1[:, [0, 1, 3, 4]]

array([[1, 2, 4, 5],
       [2, 3, 5, 6],
       [3, 4, 6, 7]])

In [41]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [43]:
arr_range = np.arange(1, 11)
arr_range
arr_range.reshape(2, 5)



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])